### PR TITLE
Retry gradle command

### PR DESCRIPTION
**Pull request by godrei**

### CODE REVIEW

**Comment by bootstraponline** [comment]
Hey, this looks great however there are a bunch more gradle specific transient errors that would benefit from a retry. Should I post a list here with examples?

**Comment by viktorbenei** [comment]
@bootstraponline sure, just create a new issue here, for easier tracking

**Comment by bootstraponline** [comment]
> @bootstraponline sure, just create a new issue here, for easier tracking

Cool, I will create the issue either today or early next week.

**Comment by viktorbenei** [comment]
Perfect, thank you @bootstraponline ! :)

**Pull request merged**
